name: Build OpenSSL 3

env:
  DEBUG_CLEAN_UP_MY_TEMP_FOLDERS_AND_FILES_ON_EXIT: '1'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build ${{ matrix.SSL_VERSION }} on ${{ matrix.IMAGE }}
    timeout-minutes: 150
    strategy:
      fail-fast: false
      matrix:
        # SSL_VERSION: ["3.5.5", "3.0.19", "3.3.6", "3.4.4", "3.6.1"]
        SSL_VERSION: ["3.5.5", "3.0.19"]
        # IMAGE: ["debian:jessie", "multiarch/debian-debootstrap:arm64-jessie", "multiarch/debian-debootstrap:armhf-jessie"]
        # IMAGE: ["debian:jessie", "multiarch/debian-debootstrap:arm64-jessie", "multiarch/debian-debootstrap:armhf-stretch", "multiarch/debian-debootstrap:armhf-buster", "multiarch/debian-debootstrap:armhf-bullseye", "multiarch/debian-debootstrap:armhf-jessie", "alpine:3.7", "multiarch/alpine:arm64-v3.7", "multiarch/alpine:armhf-v3.7", "i386/debian:jessie"]
        # IMAGE: ["debian:jessie", "multiarch/debian-debootstrap:armhf-stretch", "multiarch/debian-debootstrap:armhf-buster", "multiarch/debian-debootstrap:armhf-bullseye", "i386/debian:jessie"]
        IMAGE: ["multiarch/debian-debootstrap:arm64-jessie"]
        

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bootstrap
      uses: devizer/devops-library@main

    - name: Setup Variables
      run: |
         echo "SSL_VERSION=${{ matrix.SSL_VERSION }}" | tee -a $GITHUB_ENV
         echo "IMAGE=${{ matrix.IMAGE }}" | tee -a $GITHUB_ENV

         # tag=$(echo "${{ matrix.IMAGE }}" | awk -F":" '{print $2}')
         tag="${{ matrix.IMAGE }}"
         tag="${tag//:/-}"
         tag="${tag//\//-}"
         ARTIFACT_NAME="${{ matrix.SSL_VERSION }} on $tag"
         echo "ARTIFACT_NAME=$ARTIFACT_NAME" | tee -a $GITHUB_ENV


    - name: STEP-Run-Container.sh ${{ matrix.SSL_VERSION }} on ${{ matrix.IMAGE }}
      run: bash -eu -o pipefail OpenSSL3/STEP-Run-Container.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}
        overwrite: true
        compression-level: 9

  Builtin:
    name: Benchmark Builtin
    timeout-minutes: 120

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Bootstrap
      uses: devizer/devops-library@main
    - name: OpenSSL3/Benchmark-Builtin-OpenSSL.sh
      run: bash -eu -o pipefail OpenSSL3/Benchmark-Builtin-OpenSSL.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Builtin-Benchmarks.zip
        path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}
        overwrite: true
        compression-level: 9

  Combine:
    runs-on: ubuntu-latest
    needs: [Build, Builtin]
    if: always()
    timeout-minutes: 45
    steps:

    - uses: actions/checkout@v4
    - uses: devizer/devops-library@main
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
      with:
         path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}

    - name: Pack 7z
      shell: bash
      run: | 
        set -eu; set -o pipefail
        cd "$SYSTEM_ARTIFACTSDIRECTORY"
        find -name "OpenSSL"*".Benchmark.Summary.txt" | sort | while IFS= read -r file; do
          cat "$file" >> TOTAL.BENCHMARK.TXT
        done 
        cat TOTAL.BENCHMARK.TXT
        time 7z a -sdel -mx=9 -ms=on -mqs=on "Combined OpenSSL 3 Matrix.7z";

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: 'Combined OpenSSL 3 Matrix.7z'
        path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}
        overwrite: true
        compression-level: 1

